build:
	cargo build --release --target wasm32-unknown-unknown

test:
	cargo test

clean:
	cargo clean

fmt:
	cargo fmt

clippy:
	cargo clippy --all-targets --all-features

.PHONY: build test clean fmt clippy
